version: '3.0'
services:
  rabbitmq:
    image: 'rabbitmq:management'
    hostname: 'rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'

  database:
    image: mongo:latest
    hostname: database
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  producer:
    build: ./producer
    hostname: ejapi
    depends_on:
      - rabbitmq
    environment:
      NODE_ENV: "development"
    restart: unless-stopped
    volumes:
      - "./:/usr/src/app"
    links:
      - rabbitmq
    ports:
      - "3000:3000"

  user:
    build: ./consumers/user
    depends_on:
      - rabbitmq
      - database
    environment:
      NODE_ENV: "development"
    restart: unless-stopped
    volumes:
      - "./:/usr/src/app"
    links:
      - rabbitmq
      - database

  badge:
    build: ./consumers/badge
    depends_on:
      - rabbitmq
    environment:
      NODE_ENV: "development"
    restart: unless-stopped
    volumes:
      - "./:/usr/src/app"
    links:
      - rabbitmq

  crypto:
    build: ./consumers/crypto
    depends_on:
      - rabbitmq
    environment:
      NODE_ENV: "development"
    restart: unless-stopped
    volumes:
      - "./:/usr/src/app"
    links:
      - rabbitmq

  nginx:
    image: nginx
    restart: unless-stopped
    volumes:
      - "./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf"
      - "./frontend:/usr/src/app/frontend"
    links:
      - producer:ejapi
    depends_on:
      - producer
    ports:
      - "80:80"
    environment:
      - NGINIX_PORT=80
      - NGINX_HOST=localhost
